FROM alpine:3.23.3 AS build
WORKDIR /app
COPY . .

#also changing to non root user
FROM nginxinc/nginx-unprivileged:1.28-alpine AS production 
COPY --from=build /app/. ./usr/share/nginx/html
USER nginx
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]